//get all
GET http://localhost:3000/palettes
###
//get one
GET http://localhost:3000/palettes/664e533854ca9558f9fb56d0
###
//create 
POST http://localhost:3000/palettes
Content-Type: application/json

{
  "title": "Shimmer Sunset",
  "description": " ",
  "colors": [
    	"#ee5d6c",
      "#ce4993",
      "#6a0d83"
  ],
  "tags": [

  ],
  "date_created": "2024-05-20",
  "date_modified": "2024-05-20",
  "favorite": false
}
###
//update 
PUT http://localhost:3000/palettes/665a1650aa736d3b6d344801
Content-Type: application/json

{
  "title": "Shimmer Sunset",
  "description": " ",
  "colors": [
    	"#ee5d6c",
      "#ce4993",
      "#6a0d83", 
      "#fb9062"
  ],
  "tags": [

  ],
  "date_created": "2024-05-20",
  "date_modified": "2024-05-20",
  "favorite": false
}
###
//delete
DELETE http://localhost:3000/palettes/664f93086a555f9ee7350da4
###

# Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "John smith",
  "email": "johnsmith@example.com",
  "password": "password123"
}

###

# Login with the registered user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "password123"
}

###

# Logout the authenticated user
GET http://localhost:3000/auth/logout



// ********* RENDER LINKS ********* //

//get all
GET https://colorcollection.onrender.com/palettes
###
//get one
GET https://colorcollection.onrender.com/palettes/664e533854ca9558f9fb56d2
###
//create 
POST https://colorcollection.onrender.com/palettes
Content-Type: application/json

{
  "title": "Hip Swampy",
  "description": "Get down and dirty but also fresh and clean? ",
  "colors": [
    "#a49e8d",
    "#504135",
    "#689689",
    "#b2e6d4",
    "#83e8ba"
  ],
  "tags": [
    "minimalist",
    "neutral",
    "simple"
  ],
  "date_created": "2024-05-20",
  "date_modified": "2024-05-20",
  "favorite": false
}
###
//update 
PUT https://colorcollection.onrender.com/palettes/664ebeb0ed6712f41c7a7245
Content-Type: application/json

{
  "title": "Hip Swamp extra",
  "description": "Get down and dirty but also fresh and clean? ",
  "colors": [
    "#a49e8d",
    "#504135",
    "#689689",
    "#b2e6d4",
    "#83e8ba"
  ],
  "tags": [
    "minimalist",
    "neutral",
    "simple"
  ],
  "date_created": "2024-05-20",
  "date_modified": "2024-05-20",
  "favorite": false
}
###
//delete
DELETE https://colorcollection.onrender.com/palettes/664ebeb0ed6712f41c7a7245
###

# Register a new user
POST https://colorcollection.onrender.com/auth/register
Content-Type: application/json

{
  "name": "John smith",
  "email": "johnsmith@example.com",
  "password": "password123"
}

###

# Login with the registered user
POST https://colorcollection.onrender.com/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "password123"
}

###

# Logout the authenticated user
GET https://colorcollection.onrender.com/auth/logout
